services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: TestcontainersDemo.WebApi/Dockerfile
    ports:
      - 5167:80
      - 7137:443